import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { Header } from 'next/dist/lib/load-custom-routes'


function Home() {
  return (
    <>
         <Head>
        <title>Praveen V | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' '> 
{/* Navbar start */}
<header>
<div className='fixed flex  w-full gap-5 justify-center items-center pb-10'>
    <div className=' h-12 w-full bg-slate-400  items-center flex '>
    
        <div className='max-w-6xl mx-auto  flex justify-center gap-5 text-2xl'>
            
            <Link href="/Home/#section1"><h1>Home</h1></Link>
            <Link href="/Home/#section2"><h1>About me</h1></Link>
            <Link href="/Home/#section3"><h1>Project</h1></Link>
            <Link href="/Home/#section4"><h1>Contact</h1></Link>
        
            </div>
        </div>
    </div>
    </header>
    {/* Navbar end */}
<main className=''>
    <div className='max-w-6xl mx-auto'>

    {/* Section 1 start */}
    <div id='section1'>
        <div className='h-screen '>
        <h1>section 1</h1>
        </div>
        
    </div>
    {/* Section 1 end */}


    {/* Section 2 start */}
    <div id='section2'>
        <div className='h-screen '>
        <h1>section 2 </h1>
        </div>
        
    </div>
    {/* Section 2 end */}

    {/* Section 3 start */}
    <div id='section3'>
        <div className='h-screen '>
        <h1>section 3</h1>
        </div>
        
    </div>
    {/* Section 3 end */}

    {/* Section 4 start */}
    <div id='section4'>
        <div className='h-screen '>
        <h1>section 4</h1>
        </div>
       
    </div>
    {/* Section 4 end */}
    </div>
    </main>
   
   
   
   
    {/* Footer start*/}
    
    
    <div>
        <div className='  h-56 bg-gray-900'>
            <div className=' max-w-6xl mx-auto'>
            <h1>footer</h1>
            </div>
        
        </div>
        
    </div>
    {/* Footer end */}
    </div>
    </>
  )
}

export default Home
