import Head from 'next/head'

import Home from './Home'

export default function Index() {
  return (
    <div >
      <Head>
        <title>Praveen V | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home/>
   
    </div>
  )
}
